CREATE TABLE IF NOT EXISTS QUESTIONS
(
    ID   int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TEXT varchar(200)
);

CREATE TABLE IF NOT EXISTS QUESTIONS_ANSWERS
(
    ID               int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QUESTION_ID      int NOT NULL,
    TEXT             varchar(200),
    PERSONALITY_SIGN varchar(50),
    foreign key (QUESTION_ID) REFERENCES QUESTIONS (ID)
);
